/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-container": "#8083ff",
        "surface-bright": "#353943",
        "tertiary-fixed-dim": "#4edea3",
        "on-secondary": "#00354a",
        "on-error": "#690005",
        "surface-variant": "#31353f",
        "secondary-fixed-dim": "#7bd0ff",
        "inverse-primary": "#494bd6",
        "tertiary-container": "#00885d",
        "outline-variant": "#464554",
        "on-primary-container": "#0d0096",
        "on-tertiary-container": "#000703",
        "inverse-surface": "#dfe2ef",
        "tertiary-fixed": "#6ffbbe",
        "on-background": "#dfe2ef",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed-variant": "#005236",
        "primary": "#c0c1ff",
        "secondary": "#7bd0ff",
        "inverse-on-surface": "#2c303a",
        "surface-dim": "#0f131c",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-tertiary": "#003824",
        "background": "#0f131c",
        "surface-container-lowest": "#0a0e17",
        "on-surface-variant": "#c7c4d7",
        "secondary-fixed": "#c4e7ff",
        "on-primary": "#1000a9",
        "on-error-container": "#ffdad6",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#004c69",
        "surface-container": "#1c1f29",
        "surface-container-highest": "#31353f",
        "on-secondary-fixed": "#001e2c",
        "surface": "#0f131c",
        "surface-container-low": "#181b25",
        "primary-fixed": "#e1e0ff",
        "on-secondary-container": "#00374d",
        "surface-tint": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "outline": "#908fa0",
        "tertiary": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "surface-container-high": "#262a34",
        "secondary-container": "#00a6e0",
        "on-surface": "#dfe2ef",
        "error-container": "#93000a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "margin": "2rem",
        "gutter": "1.5rem",
        "space-xs": "0.25rem",
        "space-md": "1rem"
      },
      "fontFamily": {
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "code-block": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Geist", "sans-serif"],
        "display-hero-mobile": ["Geist", "sans-serif"],
        "telemetry-badge": ["JetBrains Mono", "monospace"],
        "display-hero": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "label-caps": ["10px", { "lineHeight": "12px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["22px", { "lineHeight": "30px", "letterSpacing": "-0.015em", "fontWeight": "500" }],
        "code-block": ["13px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "display-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "telemetry-badge": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "-0.005em", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
